name: DP_metabar
channels:
  - conda 
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
 - python=3.10.15
 - r-base=4.3.3
 - r-tidyverse=2.0.0
 - r-ape=5.8
 - r-bayestestr=0.15.0
 - r-betapart=1.6
 - r-brms=2.19
 - r-castor=1.8.2
 - r-ggplot2=3.5.1
 - r-patchwork=1.3.0
 - r-performance=0.12.2
 - r-picante=1.8.2
 - r-phytools=2.3_0
 - r-taxonomizr=0.10.6
 - r-writexl=1.5.1
 - r-vegan=2.6_4
 - bioconductor-dada2=1.30.0
 - bioconductor-shortread=1.60.0
 - bioconductor-biostrings=2.70.1
 - bioconductor-decipher=2.30.0
 - bioconductor-phyloseq=1.46.0
 - cutadapt=4.6=py310h4b81fae_1
 - blast=2.16.0
 - fasttree=2.1.11