name: DP_metabar
channels:
  - conda 
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
 - python=3.10.15
 - r-base=4.3.3
 - r-tidyverse=2.0.0
 - bioconductor-dada2=1.30.0
 - bioconductor-shortread=1.60.0
 - bioconductor-biostrings=2.70.1
 - bioconductor-decipher=2.30.0
 - cutadapt=4.6=py310h4b81fae_1